### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by kraymondksc** [jkingsman/plex-shared-library-downloader#11]
Hi, with version 0.1.5 of the extension and Plex server version 1.29.0.6244, I'm getting a 400 Bad Request when clicking on the download icon.

**Comment by jkingsman** [comment]
Hm okay. Seems like we're in a bit of a no-man's land of certain URI params working in some versions but not others. I'll see if I can untangle a common thread if I get some time next week; sorry! I'm under water with other commitments right now.

**Comment by jkingsman** [comment]
Please see https://github.com/jkingsman/plex-shared-library-downloader/issues/12#issuecomment-1327894436 -- tl;dr I can't keep up the cat and mouse game so I'm gonna archive this project.
