### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by saith89** [jkingsman/plex-shared-library-downloader#4]
the extension stopped working. when I inspect a page on Plex, it looks like "data-qa-id" was changed to "data-testid"

**Comment by jkingsman** [comment]
Ah, thanks for letting me know. I'm extremely busy this week but will try to take a look this weekend.

**Comment by saith89** [comment]
no problem, I found a workaround in the meantime by editing the "Mark as Played" button on a Plex page to include the correct attribute. the extension then adds the button for me to click. but obviously that's slow to do every time lol. EDIT: I just figured out I can just use Pip Longrun's Plex Downloader instead lol

I also have no idea if this is something affecting everyone or just me

**Comment by jkingsman** [comment]
Well it looks like Pip Longrun's site is down and also that I have a totally different UI than I designed this for. This will take a tad more work; sounds like using the script directly if you have a local copy is the best bet for tight now.

**Comment by therealmichaelberna** [comment]
I set up a mirror of pip's code as available on wayback machine, but it still isn't working for me. Seems that Plex patched this. Feel free to use, here's the link.
https://cdn.jsdelivr.net/gh/therealmichaelberna/Plex-Downloader-Javascript@main/plxdwnld bookmarklet.js

**Comment by saith89** [comment]
> I set up a mirror of pip's code as available on wayback machine, but it still isn't working for me. Seems that Plex patched this. Feel free to use, here's the link.
> https://cdn.jsdelivr.net/gh/therealmichaelberna/Plex-Downloader-Javascript@main/plxdwnld bookmarklet.js

the link doesn't work for me. this is the message I get
"Couldn't find the requested file /plxdwnld in therealmichaelberna/Plex-Downloader-Javascript."

EDIT: oh I see what happened. here's the link https://cdn.jsdelivr.net/gh/therealmichaelberna/Plex-Downloader-Javascript@main/plxdwnld%20bookmarklet.js

and here's the bookmark to run the code, you'll have to copy and paste it into a new bookmark. but like therealmichealberna said, it's not working. [javascript:(function()%7Bif (typeof plxDwnld %3D%3D 'undefined') %7Bconst jsCode %3D document.createElement('script')%3BjsCode.setAttribute('src'%2C 'https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftherealmichaelberna%2FPlex-Downloader-Javascript%40main%2Fplxdwnld%2520bookmarklet.js%3Fts%3D' %2B Math.floor(Date.now()%2F1000))%3Bdocument.body.appendChild(jsCode)%3B%7D else %7BplxDwnld.init()%3B%7D%7D)()](url)

If you use it on some non plex pages (like a google search page) it shows the message "You are currently not browsing or logged into a Plex web environment.". so it's *partially* working, at least to show that message. but it's not working on Plex

**Comment by jkingsman** [comment]
Sadly that code has been mangled by archive.org as if it were a generic page and not a bookmark let; some surgery will be required if I could get it working at all. I'll search my archives later this week and see if I've got a version saved somewhere.

@piplongrun are you still around? Do you perhaps have a recent version of the script you'd be willing to share please? Hope everything's alright with you :) 

Edit -- found it in pip's GH repo https://github.com/piplongrun/piplongrun.github.io/tree/master/plxdwnld. Will dig on this later in the week.

**Comment by chivigoku** [comment]
Hi guys,

Here is another user with the same issue.
Let´s see if this can be solved soon.

cheers

**Comment by jkingsman** [comment]
Hey folks! Thanks for your patience; it's been a busy few weeks. I've included Pip's script in the extension to work around it going away (hope everything's alright with them).

I've also reworked how the download button is injected to add it to the right of the title, which will hopefully be a little more resilient to UX changes or at least make updating it when it changes easier.

I submitted the new package version to Google minutes ago so assuming I don't get rejected for some reason or another, you should see the new version in a few hours. I'm going to keep this issue open until I've confirmed things are released.

![screenshot](https://user-images.githubusercontent.com/2365891/132249397-ffaa8b70-cb82-4069-94d4-8bed76fa8db0.png)

**Comment by jkingsman** [comment]
New version has been approved and I've confirmed it's working!
