### ISSUE TITLE
Not working again?

### ISSUE THREAD

**Issue by tarunVreddy** [jkingsman/plex-shared-library-downloader#9]
Seems like a cat and mouse game with Plex. Not sure what is going on but the chrome extension no longer shows the download button.

**Comment by jkingsman** [comment]
Oof okay. Thanks for letting me know. I'll try to take a look this upcoming weekend.

**Comment by SmilerRyan** [comment]
For me, the button shows  on both TV and movies, but clicking redirects me to a **403 Forbidden** page, instead of starting the download. The link does contain the X-Plex-Token in it which I believe to be correct.

**Comment by tarunVreddy** [comment]
Yes.. @SmilerRyan is correct. After restarting browser I see the download button, but can't download.

**Comment by jkingsman** [comment]
I spent some time on this this evening. Sounds like you two are having two separate problems, and I've discovered a third. @tarunVreddy are you using app.plex.tv? That's the only place this will appear; it doesn't work when directly connected to a server via IP or domain name.

@SmilerRyan I'm having a hard time replicating your issue, sorry. I only inherited this script and to be honest a lot of the logic is cargo culting, so if it's managing to get to the point of a download initiation but then rejecting you, I have very little clue what could possibly be going wrong.

I'm gonna spend some more time this weekend, but we may be SOL.

@piplongrun, are you still invisible? Any chance of a hail mary from you please? 👼

**Comment by katurian** [comment]
I am using app.plex.tv. Also receiving that "403 Forbidden" error.

**Comment by chris-ray** [comment]
Same "403 Forbidden" error for me, using app.plex.tv.

**Comment by Gojobriel** [comment]
no sound when downloading

**Comment by jkingsman** [comment]
I've gotten reports of a broader 403 case now, and suspicions that Plex has made the original file inaccessible via standard guest access API. I'm on vacation right now, but will dig in a bit further once I'm back next week. It may be time to delist this from the store if the lion's share of devices aren't going to work with it. For better or worse, I don't have Pip Longrun's expertise around Plex APIs and am not equipped for a deep debugging -- this has always been a wrapper more than an ownership case, so if the time of non-usefulness has come, so be it haha 🙂

**Comment by FoxtrotGolf** [comment]
I have added PR #10 with a fix for this issue a few minutes ago. Problem is related to the server side enforcement of the download privilege. With the current version of the add-on only plex pass users with granted download permission and the owners of the librarys are able to get a working download.

Disadvantage is that the download ist just named file."extension". To address this in the future, i'm thinking about using the Plex-API to get the original file name and start the download with this information.

**Comment by jkingsman** [comment]
Please see https://github.com/jkingsman/plex-shared-library-downloader/issues/12#issuecomment-1327894436 -- tl;dr I can't keep up the cat and mouse game so I'm gonna archive this project.
